### ISSUE TITLE
Concourse lite 2.0.2 Not connecting to network

### ISSUE THREAD

**Issue by zgagnon** [concourse/concourse-lite#9] opened 2016-09-06 18:13 UTC
Hi,

When using Concourse lite through vagrant 1.8.4 with Virtualbox 5.0.26 we have a problem where it is not capable of connecting to network. Vagrant file attached.

Viewing the ubuntu boot logs, there are no obvious errors. It reaches a spot where it is waiting for network to come up, waits for 60 seconds, then fails.

[Vagrantfile.txt](https://github.com/concourse/concourse-lite/files/457449/Vagrantfile.txt)

**Comment by miroswan** [comment] 2016-09-15 17:25
+1

**Comment by miroswan** [comment] 2016-09-16 17:03
There doesn't appear to be a proper network config on Vagrant up:

![screen shot 2016-09-16 at 10 01 58 am](https://cloud.githubusercontent.com/assets/3710241/18594412/b4395ae6-7bf4-11e6-94a0-57cd6938485d.png)

**Comment by miroswan** [comment] 2016-09-16 22:14
dhclient get's stuck on DHCPDISCOVER

**Comment by miroswan** [comment] 2016-09-17 02:27
Oddly enough, when I build the VM and import it from master, it works just fine. Would it make sense to tag the releases in Github as well so we can revert to a previous version to troubleshoot at a given point in time?

**Comment by nickithewatt** [comment] 2016-09-17 03:22
+1 hitting this issue too

**Comment by zgagnon** [comment] 2016-09-20 20:31
I discovered the image set up in virtualbox has the cable unplugged. Manually clicking the "cable connected" checkbox on eth0 for the box solved this problem for me.

**Comment by DanielJonesEB** [comment] 2016-09-21 16:36
I suffered the same issue as @zgagnon on 2.2.0

**Comment by miroswan** [comment] 2016-09-24 19:42
[vboxmanage](https://www.virtualbox.org/manual/ch08.html)
```
--cableconnected<1-N> on|off: This allows you to temporarily disconnect a virtual network interface, as if a network cable had been pulled from a real network card. This might be useful for resetting certain software components in the VM.
```

**Comment by miroswan** [comment] 2016-09-24 19:45
Also, this: [Packer VirtualBox Builder](https://www.packer.io/docs/builders/virtualbox-iso.html#vboxmanage)

**Comment by vito** [comment] 2016-09-26 17:44
I'm pretty sure things work after upgrading to VirtualBox 5.1.x, which is the version we now build with in CI. They must've changed something about that from 5.0.x.

**Comment by miroswan** [comment] 2016-09-26 19:17
Just confirmed that upgrading to 5.1.x does fix the issue.

**Comment by vito** [comment] 2016-09-27 18:10
Closing this since it sounds like a VirtualBox regression. Upgrading works, or using the previously mentioned workaround (`--cableconnected1`).

**Closed by vito** 2016-09-27 18:10 UTC
Labels: in-flight
